name: Build Booty Busters Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Android APK
        working-directory: ./apps/admin-mobile
        run: |
          npm run build:android || npm run android-build || echo "Run your android build command here"
          # Replace with your actual android build command e.g. 'eas build --platform android --non-interactive'

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v3
        with:
          name: booty-busters-android
          path: |
            apps/admin-mobile/build/*.apk
            apps/admin-mobile/build/*.aab

  build-ios:
    name: Build iOS IPA
    runs-on: macos-latest
    needs: build-android
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build iOS IPA
        working-directory: ./apps/admin-mobile
        run: |
          npm run build:ios || npm run ios-build || echo "Run your ios build command here"
          # Replace with your actual ios build command e.g. 'eas build --platform ios --non-interactive'

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v3
        with:
          name: booty-busters-ios
          path: |
            apps/admin-mobile/build/*.ipa

  build-windows:
    name: Build Windows App
    runs-on: windows-latest
    needs: [build-android, build-ios]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Windows App
        working-directory: ./apps/client-web
        run: |
          npm run build || echo "Run your windows build command here"
          # Replace with your actual windows build command

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: booty-busters-windows
          path: |
            apps/client-web/build/**

